spring.application.name=backend
server.port=${PORT:8080}

# Neon PostgreSQL Database Connection
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-flat-butterfly-amt3dcr5-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_fPaEJN5nypT7}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# JWT Secret
jwt.secret=${JWT_SECRET:55d285b546b3fefe2139dcad7096739ea100b40ec4be5ed603ec5e9541577789}
jwt.expiration=86400000
