spring.application.name=backend
server.port=8080

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=2007

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Secret (In production, load this from environment variable)
jwt.secret=55d285b546b3fefe2139dcad7096739ea100b40ec4be5ed603ec5e9541577789
jwt.expiration=86400000
